In [1]:
import pandas as pd

df = pd.read_csv("../data/ecommerce_sales.csv")
df.columns = df.columns.str.strip()

intäkt_per_kategori = (
    df.groupby("category")
    .agg(total_intäkt=("revenue", "sum"))
    .reset_index()
    .sort_values("total_intäkt", ascending=False)
    .reset_index(drop=True)
)

display(intäkt_per_kategori)

bästa_kategori = intäkt_per_kategori.iloc[0]

display(bästa_kategori)

intäkt_per_stad = (
    df.groupby("city")
    .agg(total_intäkt=("revenue", "sum"))
    .reset_index()
    .sort_values("total_intäkt", ascending=False)
    .reset_index(drop=True)
)

display(intäkt_per_stad)

bästa_stad = intäkt_per_stad.iloc[0]

display(bästa_stad)

      category  total_intäkt
0  Electronics    1364228.07
1       Sports     734653.42
2     Clothing     586744.91
3         Home     511070.87
4       Beauty     163053.97
5         Toys     143015.99

category        Electronics
total_intäkt     1364228.07
Name: 0, dtype: object

        city  total_intäkt
0  Stockholm    1227201.94
1   Göteborg     859019.65
2      Malmö     567926.32
3    Uppsala     551478.42
4   Västerås     297140.90

city             Stockholm
total_intäkt    1227201.94
Name: 0, dtype: object